#!/bin/sh

if [ "$(/system/bin/dumpsys power|grep mScreenOn=false)" != "" ]; then
	# set bootclasspath
	INITFILE="/init.rc"
	if [ "$(cat /init.rc | grep BOOTCLASSPATH)" = "" ]; then
		INITFILE="/init.environ.rc"
	fi
	`cat $INITFILE | grep BOOTCLASSPATH | sed 's/BOOTCLASSPATH /BOOTCLASSPATH=/g'`

	# wake up android
	PATH=/system/bin:$PATH LD_LIBRARY_PATH=/system/lib:/vendor/lib /system/bin/input keyevent 26
fi

